# ================================================================
# KONFIGURASI LOEWIX LOCAL RTSP BRIDGE
# PT. LOEWIX INDONESIA
# ================================================================
# Masukkan URL RTSP lokal kamera CCTV di kantor / gedung Anda:
RTSP_LOCAL=rtsp://admin:@192.168.11.182:554/user=admin&password=&channel=1&stream=0.sdp

# Nama stream path di cloud (sesuaikan dengan ID kamera di web Loewix):
STREAM_NAME=cam_live_5018

# Host server MediaMTX cloud Loewix:
CLOUD_SERVER=stream.loewixcctv.com
CLOUD_RTSP_PORT=8554
CLOUD_RTMP_PORT=1935
